[workspace]
resolver = "2"
members = [
    "lib",
    "node",
    "webclient",
    "collector",
]

[workspace.lints.clippy]
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
indexing_slicing = "warn"
