services:
  webclient:
    build:
      context: .
      dockerfile: Dockerfile.webclient
      args:
        BOOTSTRAP_NODE_URL: node1:6345
    ports:
      - "8081:80"

  node1:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "6345:6345"
      - "6512:6512"
    environment:
      - RUST_LOG=debug
      - ADVERTISE_HOST=node1
      - IS_BOOTSTRAP=true
      - NODE_PORT=6512
      - API_PORT=6345
      - STABILIZATION_INTERVAL=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6345/ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "6346:6346"
      - "6513:6513"
    environment:
      - RUST_LOG=debug
      - ADVERTISE_HOST=node2
      - BOOTSTRAP_ADDRESS=node1:6512
      - NODE_PORT=6513
      - API_PORT=6346
      - STABILIZATION_INTERVAL=1
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6346/ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  node3:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "6347:6347"
      - "6514:6514"
    environment:
      - RUST_LOG=debug
      - ADVERTISE_HOST=node3
      - BOOTSTRAP_ADDRESS=node1:6512
      - NODE_PORT=6514
      - API_PORT=6347
      - STABILIZATION_INTERVAL=1
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6347/ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  node4:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "6348:6348"
      - "6515:6515"
    environment:
      - RUST_LOG=debug
      - ADVERTISE_HOST=node4
      - BOOTSTRAP_ADDRESS=node1:6512
      - NODE_PORT=6515
      - API_PORT=6348
      - STABILIZATION_INTERVAL=1
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6348/ping"]
      interval: 5s
      timeout: 3s
      retries: 5
