services:
  webclient:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
