services:
  webclient:
    build:
      context: .
      dockerfile: Dockerfile.webclient
      args:
        BOOTSTRAP_NODE_URL: localhost:8080
        COLLECTOR_URL: http://collector:8765
        API_PROTOCOL: http
    ports:
      - "8088:80"

  node1:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8080:8080"
      - "6512:6512"
    environment:
      - RUST_LOG=debug
      - ADVERTISE_P2P_HOST=node1
      - ADVERTISE_P2P_PORT=6512
      - BIND_P2P_PORT=6512
      - BIND_API_PORT=8080
      - ADVERTISE_API_HOST=node1
      - ADVERTISE_API_PORT=8080
      - IS_BOOTSTRAP=true
      - STABILIZATION_INTERVAL=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8081:8081"
      - "6513:6513"
    environment:
      - RUST_LOG=debug
      - ADVERTISE_P2P_HOST=node2
      - ADVERTISE_P2P_PORT=6513
      - BIND_P2P_PORT=6513
      - BIND_API_PORT=8081
      - ADVERTISE_API_HOST=node2
      - ADVERTISE_API_PORT=8081
      - BOOTSTRAP_ADDRESS=node1:6512
      - STABILIZATION_INTERVAL=1
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  node3:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8082:8082"
      - "6514:6514"
    environment:
      - RUST_LOG=debug
      - ADVERTISE_P2P_HOST=node3
      - ADVERTISE_P2P_PORT=6514
      - BIND_P2P_PORT=6514
      - BIND_API_PORT=8082
      - ADVERTISE_API_HOST=node3
      - ADVERTISE_API_PORT=8082
      - BOOTSTRAP_ADDRESS=node1:6512
      - STABILIZATION_INTERVAL=1
    depends_on:
      node2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  node4:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "8083:8083"
      - "6515:6515"
    environment:
      - RUST_LOG=debug
      - ADVERTISE_P2P_HOST=node4
      - ADVERTISE_P2P_PORT=6515
      - BIND_P2P_PORT=6515
      - BIND_API_PORT=8083
      - ADVERTISE_API_HOST=node4
      - ADVERTISE_API_PORT=8083
      - BOOTSTRAP_ADDRESS=node1:6512
      - STABILIZATION_INTERVAL=1
    depends_on:
      node3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    ports:
      - "8765:8765"
    environment:
      - RUST_LOG=info
      - BOOTSTRAP_NODE_API_URL=http://node1:8080
      - COLLECTOR_BIND_ADDRESS=0.0.0.0:8765
      - METRICS_FETCH_INTERVAL_SECS=5
      - SQLITE_DB_PATH=/app/data/metrics.sqlite
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/metrics"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - collector_db:/app/data

volumes:
  collector_db:
