apiVersion: apps/v1
kind: Deployment
metadata:
  name: tace-node
  namespace: tace-chat
  labels:
    app: tace-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tace-node
  template:
    metadata:
      labels:
        app: tace-node
    spec:
      containers:
      - name: tace-node
        image: ${DOCKER_USERNAME}/tace-node:${GITHUB_REF_NAME}
        env:
        - name: ADVERTISE_HOST
          value: bootstrap.tace.chat
        - name: IS_BOOTSTRAP
          value: "true"
        ports:
        - containerPort: 6345
          name: api
        - containerPort: 6512
          name: p2p
---
apiVersion: v1
kind: Service
metadata:
  name: tace-node-api
  namespace: tace-chat
spec:
  selector:
    app: tace-node
  ports:
    - protocol: TCP
      port: 6345
      targetPort: 6345
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tace-node-p2p
  namespace: tace-chat
spec:
  selector:
    app: tace-node
  ports:
    - protocol: TCP
      port: 6512
      targetPort: 6512
  type: LoadBalancer
