name: Deploy Webclient to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build webclient
      run: wasm-pack build --target web --out-dir webclient/public/pkg webclient

    - name: Replace URLs
      run: |
        sed -i 's|__BOOTSTRAP_NODE_URL__|bootstrap.tace.chat:6345|g' webclient/public/main.js
        sed -i 's|__COLLECTOR_URL__|https://metrics.tace.chat|g' webclient/public/main.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./webclient/public
        publish_branch: gh-pages
        cname: tace.chat
