name: Deploy to Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Deploy Collector to Kubernetes
      run: |
        export DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
        export GITHUB_REF_NAME="${{ github.ref_name }}"
        envsubst < k8s/collector.yaml | kubectl apply -f -

    - name: Deploy Node to Kubernetes
      run: |
        export DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
        export GITHUB_REF_NAME="${{ github.ref_name }}"
        envsubst < k8s/node.yaml | kubectl apply -f -

    - name: Deploy Ingress to Kubernetes
      run: kubectl apply -f k8s/ingress.yaml
